- name: Setup web server
  hosts: deploy_server
  become: true
  gather_facts: true
  vars_files:
    - group_vars/env
    - group_vars/colman.env
    - group_vars/docker.env

  tasks:
    - name: Install epel-release package
      yum:
        name: epel-release
        state: present
      when: ansible_facts['distribution'] == 'Amazon' and ansible_facts['distribution_version'] == '2'

    - name: Install git, python-pip, and yum-utils
      yum:
        name:
          - git
          - python-pip
          - yum-utils
        state: present
