- name: Setup web server
  hosts: deploy_server
  become: true
  gather_facts: true
  vars_files:
    - group_vars/env
    - group_vars/colman.env
    - group_vars/docker.env

  tasks:
    - name: Install epel-release package
      yum:
        name: epel-release
        state: present
      when: ansible_facts['distribution'] == 'Amazon' and ansible_facts['distribution_version'] == '2'

    - name: Install git, python-pip, and yum-utils
      yum:
        name:
          - git
          - python-pip
          - yum-utils
        state: present
    
    - name: Install Docker from the Amazon Linux Extras repository
      yum:
        name: docker
        state: present

    - name: Add ec2-user to the Docker group
      user:
        name: ec2-user
        groups: docker 
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy SSH key to server
      copy:
        src: /home/ec2-user/.ssh/avior.pem
        dest: /home/ec2-user/.ssh/id_rsa 
        mode: '0600'
        owner: ec2-user
        group: ec2-user

    - name: Clone the app repository
      git:
        repo: 'https://github.com/AviorAtar/Final-WorkShop-CI-CD.git'
        dest: /home/ec2-user/app
        version: main

    - name: Build Docker image with sudo
      become: true
      command: docker build -t my-app:latest /home/ec2-user/app/src
    
    # - name: Login to DockerHub
    #   docker_login:
    #     username: "{{ docker_username }}"
    #     password: "{{ docker_password }}"
      
